/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef NCHATCLIENT-GUI_PRIVATE_H
#define NCHATCLIENT-GUI_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.8.176"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	8
#define VER_BUILD	176
#define COMPANY_NAME	"NotMyFaults"
#define FILE_VERSION	"1.1.8.176"
#define FILE_DESCRIPTION	"NChat Client"
#define INTERNAL_NAME	"NChatClient"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"NChatClient-GUI.exe"
#define PRODUCT_NAME	"NChat"
#define PRODUCT_VERSION	"1.1.8.176"

#endif /*NCHATCLIENT-GUI_PRIVATE_H*/
